// <auto-generated />
namespace Vulnerable.Net48.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StoredProc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoredProc));
        
        string IMigrationMetadata.Id
        {
            get { return "202105172322101_StoredProc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
