version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}vulnerableapinet48
    build:
      context: .\Vulnerable.Net48.Api
      dockerfile: Dockerfile
    environment:
      - HOSTED_IN_DOCKER=1
    ports:
      - "80:80"
    networks:
      - vulnbackendnet
  database-server:
    image: microsoft/mssql-server-windows-express
    restart: always
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    networks:
      - vulnbackendnet
networks:
  vulnbackendnet: {}  
